name: publish

on: ["push", "pull_request"]

jobs:
  make:
    runs-on: ubuntu-latest
    container: node:20.9.0
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24"

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 9.10.0
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Generate code
        run: pnpm run generate

      - name: Login to NPM
        run: "npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN"
        working-directory: "./dist"

      - name: "Update version"
        run: "npm version patch" # Only patch releases here
        working-directory: "./dist"

      - name: "Publish"
        run: "npm publish"
        working-directory: "./dist"
