name: publish

on: ["push", "pull_request"]

jobs:
  make:
    runs-on: ubuntu-latest
    container: node:20.9.0
    env:
      NPM_TOKEN: ${{ secrets.SuperSecret }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Login to NPM
        run: "npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN"
        working-directory: "./dist"
      - name: "Publish"
        run: "npm publish"
        working-directory: "./dist"
